version: '3'

services:
    web:
        image: nginx:latest
        container_name: culturevein_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/code
    database:
        image: mysql
        container_name: culturevein_database
        volumes:
            - ./mysql_init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"