#php:
#  image: php:7.0-apache
#  volumes:
#    - ./public_html:/var/www/html/
#  ports:
#    - "8000:80"
db:
  build: docker/mysql
  ports:
      - "3306:3306"
  environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"